export const ADDUSER = 'ADDUSER ';
export const UPDATEUSER = 'UPDATEUSER';
export const REMOVEUSER = 'REMOVEUSER';
export const ADDMESSAGE = 'ADDMESSAGE';
export const SETONLINEUSERS = 'SETONLINEUSERS';
export const SETONLINEROOMS = 'SETONLINEROOMS';
